# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/gabriel/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# zgenom
source "${HOME}/.zgenom/zgenom.zsh"

if ! zgenom saved; then
  zgenom ohmyzsh
  zgenom ohmyzsh plugins/git
  zgenom ohmyzsh plugins/sudo
  zgenom ohmyzsh plugins/colored-man-pages
  zgenom ohmyzsh plugins/zsh-interactive-cd
  zgenom load zsh-users/zsh-syntax-highlighting
  zgenom load desyncr/auto-ls
  zgenom load zpm-zsh/colors
  zgenom load hlissner/zsh-autopair
  zgenom load jeffreytse/zsh-vi-mode
  zgenom load zpm-zsh/ls
  zgenom load zpm-zsh/tmux
  zgenom load bric3/nice-exit-code
  zgenom save
fi
