# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
#
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/gabriel/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export TMUX_AUTOSTART=false
# zgenom
source "${HOME}/.zgenom/zgenom.zsh"

if ! zgenom saved; then
  zgenom ohmyzsh
  zgenom ohmyzsh plugins/git
  #zgenom ohmyzsh plugins/sudo
  zgenom ohmyzsh plugins/colored-man-pages
  zgenom ohmyzsh plugins/zsh-interactive-cd
  zgenom load zsh-users/zsh-syntax-highlighting
  zgenom load desyncr/auto-ls
  zgenom load zpm-zsh/colors
  zgenom load hlissner/zsh-autopair
  zgenom load jeffreytse/zsh-vi-mode
  zgenom load zpm-zsh/ls
  zgenom load zpm-zsh/tmux
  zgenom load bric3/nice-exit-code
  zgenom save
fi

alias v=nvim

bindkey -v

alias termsize='echo "width: $(tput cols)\nheight: $(tput lines)"'
alias batstate='echo "Charge state: $(cat /sys/class/power_supply/BAT0/capacity)%"'
alias clear='clear;neofetch'
alias bdin="betterdiscordctl install && killall Discord && Discord & disown"
alias upg='paru -Syu --skipreview --noconfirm && flatpak upgrade && rustup upgrade'

alias grepo="cd $HOME/Documents/repos && ls"
alias gdot="cd $HOME/dotfiles && ls"
alias vgdot="cd $HOME/dotfiles && v"

alias slol="while true;do \clear;sl --help | lolcat;done;"

# localhost.run
alias lhr="ssh -R 80:localhost:8080 nokey@localhost.run"
alias sshrpi="ssh jade@192.168.178.111"

# cargo
alias cr="cargo run"
alias cb="cargo build"
alias cf="cargo fmt"
alias cfx="cargo fix"
alias cl="cargo clippy"
alias cbr="cargo build --release"
alias msda1="sudo mount /dev/sda1 /mnt/portable-mass-storage"

# file endings
alias -s {pdf,PDF}="evince"
alias -s {jpg,JPG,png,PNG}="kitty +kitten icat"
alias -s {ods,ODS,odt,ODT,odp,ODP,doc,DOC,docx,DOCX,xls,XLS,xlsx,XLSX,xlsm,XLSM,ppt,PPT,pptx,PPTX,csv,CSV}='libreoffice'
alias -s {html,HTML}="librewolf"
alias -s {mp4,MP4,mov,MOV,mkv,MKV}='vlc'
alias -s {zip,ZIP,war,WAR}="unzip -l"
alias -s {jar,JAR}="java -jar"
alias -s gz="tar -tf"
alias -s {tgz,TGZ}="tar -tf"

# r/unixporn enjoyer moment
neofetch
